#cloud-config

hostname: lab4-worker
manage_etc_hosts: true

users:
  - name: ansible
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - YOUR_SSH_PUBLIC_KEY_HERE

write_files:
  - path: /etc/netplan/99-hostonly.yaml
    content: |
      network:
        version: 2
        ethernets:
          enp0s8:
            addresses:
              - 192.168.56.10/24

runcmd:
  - netplan apply
