server {
    listen 80;
    # Write logs for all http requests
    access_log /var/log/nginx/mywebapp_access.log;

    # http://localhost/(items) => nginx => http://127.0.0.1:5000
    location = / { proxy_pass http://mywebapp:5000; }
    location /items { proxy_pass http://mywebapp:5000; }

    # Block everything else (/health endpoints)
    location / { return 403; }
}